-- 두 번째 DB(sampledb2) 시드 데이터
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES ('P001', '노트북', 1500000);
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES ('P002', '모니터', 300000);
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES ('P003', '키보드', 50000);
