-- HSQLDB 인메모리용 스키마 (기동 시 자동 실행됨)
-- 게시판 샘플 테이블
DROP TABLE SAMPLE IF EXISTS;

CREATE TABLE SAMPLE (
    ID          VARCHAR(20)   NOT NULL,
    NAME        VARCHAR(100),
    DESCRIPTION VARCHAR(4000),
    USE_YN      CHAR(1)       DEFAULT 'Y',
    REG_USER    VARCHAR(50),
    CONSTRAINT PK_SAMPLE PRIMARY KEY (ID)
);

-- DB 에서 관리하는 REST API 클라이언트(HMAC 자격증명)
-- 자식(API_CLIENT_IP)을 먼저 DROP 해야 외래키 제약에 걸리지 않음
DROP TABLE API_CLIENT_IP IF EXISTS;
DROP TABLE API_CLIENT IF EXISTS;

CREATE TABLE API_CLIENT (
    API_KEY VARCHAR(50)  NOT NULL,
    SECRET  VARCHAR(200) NOT NULL,
    USE_YN  CHAR(1)      DEFAULT 'Y',
    CLIENT_NAME VARCHAR(100),
    CONSTRAINT PK_API_CLIENT PRIMARY KEY (API_KEY)
);

-- 클라이언트별 허용 출발지 IP 대역(CIDR). 행이 없는 클라이언트는 IP 제한 없음.
CREATE TABLE API_CLIENT_IP (
    API_KEY VARCHAR(50) NOT NULL,
    CIDR    VARCHAR(50) NOT NULL,
    CONSTRAINT PK_API_CLIENT_IP PRIMARY KEY (API_KEY, CIDR),
    CONSTRAINT FK_API_CLIENT_IP FOREIGN KEY (API_KEY) REFERENCES API_CLIENT (API_KEY)
);
