DROP TABLE SAMPLE IF EXISTS;

CREATE TABLE SAMPLE (
    ID          VARCHAR(20)   NOT NULL,
    NAME        VARCHAR(100),
    DESCRIPTION VARCHAR(4000),
    USE_YN      CHAR(1)       DEFAULT 'Y',
    REG_USER    VARCHAR(50),
    CONSTRAINT PK_SAMPLE PRIMARY KEY (ID)
);

-- REST API clients (HMAC credentials) managed in DB
DROP TABLE API_CLIENT_IP IF EXISTS;
DROP TABLE API_CLIENT IF EXISTS;

CREATE TABLE API_CLIENT (
    API_KEY VARCHAR(50)  NOT NULL,
    SECRET  VARCHAR(200) NOT NULL,
    USE_YN  CHAR(1)      DEFAULT 'Y',
    CLIENT_NAME VARCHAR(100),
    CONSTRAINT PK_API_CLIENT PRIMARY KEY (API_KEY)
);

-- allowed source IP ranges per client (CIDR). No rows for a client = no IP restriction.
CREATE TABLE API_CLIENT_IP (
    API_KEY VARCHAR(50) NOT NULL,
    CIDR    VARCHAR(50) NOT NULL,
    CONSTRAINT PK_API_CLIENT_IP PRIMARY KEY (API_KEY, CIDR),
    CONSTRAINT FK_API_CLIENT_IP FOREIGN KEY (API_KEY) REFERENCES API_CLIENT (API_KEY)
);
