-- 두 번째 DB(sampledb2) 스키마 (HSQLDB 인메모리, 데모용)
DROP TABLE PRODUCT IF EXISTS;

CREATE TABLE PRODUCT (
    PRODUCT_ID   VARCHAR(20)   NOT NULL,
    PRODUCT_NAME VARCHAR(100),
    PRICE        INTEGER,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID)
);
